debug: true
type: "node" # node / storage
transporter:
  timeout: 30 # default timeout for actions, in seconds
  heartbeatInterval: 5 # in seconds
  deliveryMethod: random
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  nats:
  p2p:
  tcp:
database:
  leveldb:
    # required database
    discovery:
      dbPath: /var/block-node/data/discovery.db
  couch_db:
    host: 127.0.0.1
    port: 5984
    username: admin
    password: admin
    prefix: "bn_"
storage:
  type: ""
