debug: true
type: node # node / storage
transport:
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  nats:
  p2p:
  tcp:
database:
  leveldb:
    main:
      dbPath: /var/block-node/data/main.db
    # required database
    discovery:
      dbPath: /var/block-node/data/discovery.db
  couch_db:
    host: 127.0.0.1
    port: 5984
    username: admin
    password: admin
    prefix: "bn_"
storage:
  type: ""
