debug: true
# service name eg "auth-service"
name: "example-service"
# service version
version: 1
# directory where data (eg databases) is stored
data_dir: "/usr/local/block-node"
# -- network settings --
network:
  # default packet delivery method: all / random
  delivery: "random"
  # transport type: tcp / redis
  transport: "tcp"
  # how often nodes should announce their presence to the network
  heartbeat_interval: 5
  # how long node should wait for response from other node/s before timing out the request
  action_timeout: 15
  # selected transport settings
  settings:
    public_host: "localhost"
    public_port: "8090"
    bind_host: "0.0.0.0"
    bind_port: "8090"
  # known nodes at startup - will send heartbeat
  nodes:
    - transport: "tcp"
      public_host: "localhost"
      public_port: "8090"
# -- database settings ---
# you can define LevelDB or SQLite databases
# database names must be unique
# there are different settings available depending on the chosen database
# for more info read documentation
database:
  myFirstDb:
    type: "leveldb"
    settings:
      write_buffer_size: 10 # in MB
  mySecondDb:
    type: "sqlite"
    settings:
      options: "cache=shared&mode=rw"
      maxOpenConnections: 1
