debug: true
type: "node" # node / storage
transporter:
  timeout: 30 # default timeout for actions, in seconds
  heartbeatInterval: 5 # in seconds
  deliveryMethod: random
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
database:
  leveldb:
    # required database
    discovery:
      dbPath: /var/block-node/data/discovery.db
      writeBufferSize: 1024
  sqlite:
    # uncomment to use
#    default:
#      path: "/var/block-node/data/default.sqlite"
#      options: "cache=shared&mode=rw"
#      maxOpenConnections: 0